// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// peakFind
LogicalVector peakFind(NumericVector ys, int win, int min);
RcppExport SEXP _tofTools_peakFind(SEXP ysSEXP, SEXP winSEXP, SEXP minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< int >::type win(winSEXP);
    Rcpp::traits::input_parameter< int >::type min(minSEXP);
    rcpp_result_gen = Rcpp::wrap(peakFind(ys, win, min));
    return rcpp_result_gen;
END_RCPP
}
// testRcp
NumericVector testRcp(int n);
RcppExport SEXP _tofTools_testRcp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(testRcp(n));
    return rcpp_result_gen;
END_RCPP
}
// read_bin_c
NumericVector read_bin_c(NumericVector ys, NumericVector pos);
RcppExport SEXP _tofTools_read_bin_c(SEXP ysSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bin_c(ys, pos));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tofTools_peakFind", (DL_FUNC) &_tofTools_peakFind, 3},
    {"_tofTools_testRcp", (DL_FUNC) &_tofTools_testRcp, 1},
    {"_tofTools_read_bin_c", (DL_FUNC) &_tofTools_read_bin_c, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tofTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
