// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// peakFind
LogicalVector peakFind(NumericVector ys, int win, int min);
RcppExport SEXP tofTools_peakFind(SEXP ysSEXP, SEXP winSEXP, SEXP minSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< int >::type win(winSEXP);
    Rcpp::traits::input_parameter< int >::type min(minSEXP);
    __result = Rcpp::wrap(peakFind(ys, win, min));
    return __result;
END_RCPP
}
// testRcp
NumericVector testRcp(int n);
RcppExport SEXP tofTools_testRcp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(testRcp(n));
    return __result;
END_RCPP
}
// read_bin_c
NumericVector read_bin_c(NumericVector ys, NumericVector pos);
RcppExport SEXP tofTools_read_bin_c(SEXP ysSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos(posSEXP);
    __result = Rcpp::wrap(read_bin_c(ys, pos));
    return __result;
END_RCPP
}
