# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' find peaks within a window
#' 
#' Not really adjusted by my needs
peakFind <- function(ys, win, min) {
    .Call('tofTools_peakFind', PACKAGE = 'tofTools', ys, win, min)
}

testRcp <- function(n) {
    .Call('tofTools_testRcp', PACKAGE = 'tofTools', n)
}

#' calculates the number of counts between indices
#' 
#' @param ys spectrum vector
#' @param pos position vector
#' @export
#' @return vector of length pos with the summed counts (first is 0)
read_bin_c <- function(ys, pos) {
    .Call('tofTools_read_bin_c', PACKAGE = 'tofTools', ys, pos)
}

