library(rhdf5)
#' TOF H5 measurement class
#' 
#' designed to hold and interact with the H5 measurment
#' data generated by Ionicon Measurement device. Hopefully this will by usefull for other devices as well.
#' 
#' @slot file.name holding the HDF5 data
#' @slot n.scans number of scans in file for easy access
#' @exportClass tof_h5
#' @name tofh5-class
#' @rdname tofh5-class
setClass("tof_h5", 
         representation(file.name='character',
         				n.scans='numeric', 
         				.meas.reader='H5IdComponent',
         				.tofblock='H5IdComponent',
         				.indexhelp='list') 
         )
 
